# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8cc81f730fa2e68e0093fd8acd2e7c3b313a1b4a7c467072063174fffab6eb95cbd5cc08d06549fe3f1c301b30751acf9720b9a873b6bbcd4252d3a690e8e49
  facebook_id:     <%= ENV['FACEBOOK_ID'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  google_api_key:       <%= ENV['GOOGLE_API_KEY'] %>
  google_client_id:     <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

test:
  secret_key_base: 37c91009cfbc52eae1ba70497058c5314a9d3ccd98f197bfa02f3184c880bcb69d34c9bbb9242b4dea1a1f1dbdeac0fadfad6b4fda34b6bf0da2b1d095c7a98e
  facebook_id:     <%= ENV['FACEBOOK_ID'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  google_api_key:       <%= ENV['GOOGLE_API_KEY'] %>
  google_client_id:     <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id:     <%= ENV['FACEBOOK_ID'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  google_api_key:       <%= ENV['GOOGLE_API_KEY'] %>
  google_client_id:     <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
